version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: litting
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
